name: CI

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: php install
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
      - name: composer install
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--no-dev"
      - name: yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx --no-install semantic-release
