name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    types:
      - "closed"

jobs:
  update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: php install
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
      - name: composer install
        uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--no-dev"
      - name: yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: yarn build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx --no-install semantic-release
